### ISSUE TITLE
Abstract continuation

### ISSUE THREAD

**Issue by RichardScottOZ** [SarthakJShetty/pyResearchInsights#4]
I didn't think I saw this - let's say you had 2K abstracts to get and your internet connection dies after 1200.

How much work to change from 'get to where it left off'?  Or add.

Rather than start doing it again.

**Comment by SarthakJShetty** [comment]
Right, we're working on this at the moment. Should be a fairly simple modification to the code. IIRC we had this functionality earlier, but decided to get rid of it since new papers kept messing up the index that we were using to keep track of the number of papers.

If someone has a fix for this, I will gladly review and accept PR. If not, I'll work on implementing this fix soon, since a lot of users have asked for this.

**Comment by RichardScottOZ** [comment]
Yeah, I guess that is tricky, but for any one 'run' can it have a 'static' index list as it was at that minute, and the 'continue' just works on the person's list at the time?

**Comment by SarthakJShetty** [comment]
Hmm that does sound interesting. I was thinking of maybe a pre-processing step that checks the index if the last retrieved index and skip those many papers/abstracts.
